version: '3'
services:
  web:
    volumes:
      - '../../../app:/opt/node_app/app'
      - '../../../lib:/opt/node_app/lib'
      - '../../../views:/opt/node_app/views'
      - '../../../public:/opt/node_app/public'
      - '../../../extensions:/opt/node_app/extensions'
      - '../../../db:/opt/node_app/db'
      - '../../../certs:/opt/node_app/certs'
      - '../../../fileUploads:/opt/node_app/fileUploads:rw'
    ports:
      - '8100:3000'
    command: 'npm run debug'
    restart: 'always'
    stdin_open: true
    tty: true
    hostname: 'ssacrm'
    build:
      context: '../../../'
      dockerfile: '.wappler/targets/Development/web/Dockerfile'
    depends_on:
      - 'db'
    logging:
      options:
        max-file: '5'
        max-size: '10m'
  db:
    image: 'mysql:8.0'
    environment:
      MYSQL_ROOT_PASSWORD: 'HgTivJ8Y'
      MYSQL_DATABASE: 'ssa-crm'
      MYSQL_USER: 'db_user'
      MYSQL_PASSWORD: '06tmxKBc'
      LANG: 'C.UTF_8'
    volumes:
      - './db_init:/docker-entrypoint-initdb.d'
    ports:
      - '9906:3306'
    restart: 'always'
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
      - '--default-authentication-plugin=mysql_native_password'
    logging:
      options:
        max-file: '5'
        max-size: '10m'
