version: '3'
services:
  db:
    image: 'mysql:8.0'
    environment:
      MYSQL_ROOT_PASSWORD: HgTivJ8Y
      MYSQL_DATABASE: ssa-crm
      MYSQL_USER: db_user
      MYSQL_PASSWORD: 06tmxKBc
    volumes:
      - './db_init:/docker-entrypoint-initdb.d'
    ports:
      - '9906:3306'
    restart: always
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
      - '--default-authentication-plugin=mysql_native_password'
  web:
    depends_on:
      - db
    volumes:
      - '../../../app:/opt/node_app/app'
      - '../../../lib:/opt/node_app/lib'
      - '../../../views:/opt/node_app/views'
      - '../../../public:/opt/node_app/public'
      - '../../../extensions:/opt/node_app/extensions'
      - '../../../fileUploads:/opt/node_app/fileUploads:rw'
    ports:
      - '80:3000'
    restart: always
    stdin_open: true
    tty: true
    build:
      context: ../../../
      dockerfile: .wappler/targets/Production/web/Dockerfile
volumes: {}
