version: '3'
services:
  db:
    environment:
      MYSQL_ROOT_PASSWORD: 'HgTivJ8Y'
      MYSQL_DATABASE: 'ssa-crm'
      MYSQL_USER: 'db_user'
      MYSQL_PASSWORD: '06tmxKBc'
    volumes:
      - 'db-volume:/var/lib/mysql'
    ports:
      - '9906:3306'
    restart: 'always'
    logging:
      options:
        max-file: '5'
        max-size: '10m'
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
      - '--default-authentication-plugin=mysql_native_password'
    build:
      context: '.'
      dockerfile: 'db/Dockerfile'
  web:
    depends_on:
      - 'db'
    ports:
      - '80:3000'
    restart: 'always'
    stdin_open: true
    tty: true
    logging:
      options:
        max-file: '5'
        max-size: '10m'
    build:
      context: '../../../'
      dockerfile: '.wappler/targets/DO-Staging/web/Dockerfile'
    volumes:
      - 'user_uploads:/opt/node_app/fileUploads:rw'
  redis:
    image: 'redis:alpine'
    hostname: 'redis'
volumes:
  db-volume: ~
  user_uploads: ~
